### ISSUE TITLE
 Move the `IsoBibliographicItem` class to the IsoBib gem.

### ISSUE THREAD

**Issue by andrew2net** [metanorma/iso-bib-item#10]
@ronaldtse @opoudjis since we extract `BibliographicItem` class from the IsoBibGem seems this gem is used only on the IsoBib. Suggest to move `IsoBibliographicIcem` class to IsoBib and delete this gem.

**Comment by ronaldtse** [comment]
Agree! Just want to be sure that other gems that depend on IsoBibliographicItem will switch their dependencies to IsoBib gem. 

I’m actually wondering if we should rename those to “relaton-iso” etc

**Comment by andrew2net** [comment]
@ronaldtse if we have more than one gem uses the `IsoBiblographicItem` then this gem should remain.
Renaming this gem cause to update all gems dependent on it. But since we extract `BibliogtaphicItem` we will have to update these gems anyway. So we can make a new "relaton-iso" gem and move `IsoBibliographicIem` class to it.

**Comment by ronaldtse** [comment]
I think GbBib uses IsoBiblographicItem, not sure if others do. Probably not?

**Comment by andrew2net** [comment]
I just checked and find out IsoBib, GbBib, IecBib, and ItuBib use IsoBibItem.

**Comment by ronaldtse** [comment]
IsoBibItem is technically only for ISO and GB models. IEC is somewhat similar, but ITU’s model is quite different.

**Comment by andrew2net** [comment]
We use a `BibliographicItem` class in 2 gems, IsoBib and GbBib. So we should move the class to a separated gem.

**Comment by ronaldtse** [comment]
@andrew2net isn’t the `BibliographicItem` class used in `relaton-bib`?

**Comment by andrew2net** [comment]
@ronaldtse we split `iso-bib-item` into `relaton-bib` and `relation-iso`. So they use `BibliographicItem` and `IsoBibliographicItem` classes respectively.
