### ISSUE TITLE
Extract out BibliographicItem to Relaton

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/iso-bib-item#8]
Having seen how NistBib inherits from this gem (`iso-bib-item`) prompted me to think that this gem is doing two things at once:

1. The implementation of the Relaton models;
2. The implementation of ISO Bibliographic models.

These two things ought to be separate. For example, NistBibliographicItem is vastly different from IsoBibliographicItem.

Thoughts @opoudjis @andrew2net ?

**Comment by andrew2net** [comment]
The `BibbliograhpicItem` item class is inherited by other gems and by `IsoBibliographicItem` class. I think a good idea to extract `BibbliograhpicItem` class to another gem, say `bib-item`. So it could be inherited without `iso-bib-item` dependency. But it needs to change a lot of gems.

**Comment by ronaldtse** [comment]
@andrew2net I agree that we should split. I think it won’t be too difficult to transition since all the gems that depend on BibItem already requires the iso-bib-item gem. If iso-bib-item depends on the relaton-bib gem then it’s fine.

**Comment by andrew2net** [comment]
@ronaldtse now `IsoBibIten::BibliographicItem` is in `IsoBibItem` namespace. If we will use `BibItem` namespace in new `bib-item` gem we should update it in all gems which use `BibliographicItem` class.

**Comment by opoudjis** [comment]
Yup.

**Comment by ronaldtse** [comment]
We call this the “relaton-bib” gem? Or should it just be part of “relaton” gem?

**Comment by opoudjis** [comment]
By default, I'd rather it be inside the relaton gem. There is no good reason for 1 class = 1 gem, each new gem has its own maintenance burden. The only exception if it becomes a mutual recursion problem for testing. Which it might.

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis let's make it clean. If we put the `BibliographicItem` class into the `relaton` gem then we have to add the `relaton` as a dependency to every gem which uses `BibbliographicItem` class. Right?

**Comment by ronaldtse** [comment]
My fear was that the “relaton” gem will include gems of different types, and those will need to include “relaton” for testing.

**Comment by andrew2net** [comment]
@ronaldtse @opoudjis I'm stuck with the question. Should I create a new `relaton-bib` gem to extract `BibliographicItem` class or move the class to the existed `relaton` gem?

**Comment by opoudjis** [comment]
... Noone's commented. I wouldn't unless there was a problem with mutual recursion, because it is disgusting enough to have to maintain 100 gems without making them 101. The problem is, it is possible that there will be a problem with mutual recursion.

What can I say. Make them separate.

**Comment by ronaldtse** [comment]
@andrew2net in this case, can we try placing the code in `relaton` gem, and if the time comes a recursion issue arises, we fix it with a new gem. How's that?

**Comment by andrew2net** [comment]
@ronaldtse I'm about finishing 2 gems `relaton-bib` and `relaton-iso`. They still need to finish tests.
I don't see any reason to put them into the `relaton` gem. I updated `BibliographicItem` and `IsoBibliographicItem` classes according to last grammars, so they became more complicated. In my opinion, 2 new gems are quite holistic. But if you insist I'll try to place them into `relaton`.

**Comment by ronaldtse** [comment]
Let’s keep them separate then. 

The reason to keep separate relaton gems is to allow other flavors to be easily added, without being tied into a single release. It’s the same strategy we use for Metanorma that seems to be working well.

**Comment by ronaldtse** [comment]
> PS Maybe we should place all bib gems into relaton?

This is a good idea. We’ve previously discussed about this but forgot why we haven’t done it. I think we should have a “relaton” gem that supports fetching all the Bib information from data sources (eg. ISO’s website is a data source). 

We can rename all the *bib gems into relaton-* gems.
