### ISSUE TITLE
Allow both YYYMM and YYYYMMDD dates

### ISSUE THREAD

**Issue by opoudjis** [metanorma/iso-bib-item#9]
I note that you have permitted YYYYMM dates, which are going to be required by NIST. But for completeness, I think you should also allow YYYYMMDD dates; so the option ":full_date" should have the values "YYYY" (default), "YYYYMMDD", and "YYYYMM".

Please ensure this option is documented in the README for this gem. 

Please ensure (if you haven't already) that nistbib uses the YYYYMD option for dates. That is the only case when YYYYMD is used; the default date format must remain YYYY (but for ietfbib and nistbib).

**Comment by andrew2net** [comment]
Implemented it in relaton-bib gem. Close the issue since we move to relaton-bib.
